# Site settings
title:          a primer to program synthesis
description:    "a practical introduction to modern program synthesis"
# baseurl:        "/tale"
url:            "https://evanthebouncy.github.io/program-synthesis-primer/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# # Author
author:
  name:         evanthebouncy
#   url:          https://chester.how
#   email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale